name: release

on:
  push:
    branches:
      - "main"
jobs:
  tag_release:
    name: "Check Commit and Create Tag"
    runs-on: ubuntu-latest
    outputs:
      should_create: ${{ steps.increment_version.outputs.CREATE_RELEASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Increment Version
        id: increment_version
        uses: ./.github/actions/release
  build:
    needs: tag_release
    if: needs.tag_release.outputs.should_create == 'true'
    name: "Create Release Artifacts"
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.tag_release.outputs.upload_url }}
      should_create: ${{ needs.tag_release.outputs.should_create }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Print Commit Message
        run: |
          git rev-list --format=%B --max-count=1 HEAD | sed '2q;d'
      - name: Extract Commit Message
        id: commit-message
        run: |
          echo "COMMIT_MSG=$(git rev-list --format=%B --max-count=1 HEAD | sed '2q;d')" >> $GITHUB_ENV
      - name: Print Tag Name
        run: |
          git tag | sort -V | tail -1
      - name: Extract Tag Name
        id: tag-name
        run: |
          echo "COMMIT_TAG=$(git tag | sort -V | tail -1)" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build Chrome Artifact
        run: |
          cp -a ./chrome/* .
          npx rollup ./main.js --file ./main.min.js --format iife
          npx rollup ./popup.js --file ./popup.min.js --format iife
          zip ./chrome-dist.zip ./icons entry.html main.min.js manifest.json popup.min.js styles.css
      - name: Build Firefox Artifact
        run: |
          cp -a ./firefox/* .
          npx rollup ./main.js --file ./main.min.js --format iife
          npx rollup ./popup.js --file ./popup.min.js --format iife
          zip ./firefox-dist.zip ./icons entry.html main.min.js manifest.json popup.min.js styles.css
      - name: Upload Chrome Artifact
        uses: actions/upload-artifact@main
        with:
          name: chrome-dist.zip
          path: chrome-dist.zip
      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@main
        with:
          name: firefox-dist.zip
          path: firefox-dist.zip
      - name: Create Release
        id: tag_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.COMMIT_TAG }}
          release_name: Release ${{ env.COMMIT_TAG }}
          body: ${{ env.COMMIT_MSG }}
          draft: false
          prerelease: false

  upload_chrome_artifact:
    needs: build
    if: needs.build.outputs.should_create == 'true'
    name: "Upload Chrome Artifact"
    runs-on: ubuntu-latest
    steps:
      - name: download chrome artifact
        uses: actions/download-artifact@main
        with:
          name: chrome-dist.zip
          path: ./
      - name: Upload Release Asset
        id: upload_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build.outputs.upload_url }}
          asset_path: ./chrome-dist.zip
          asset_name: chrome-dist.zip
          asset_content_type: application/zip
  upload_firefox_artifact:
    needs: build
    if: needs.build.outputs.should_create == 'true'
    name: "Upload Firefox Artifact"
    runs-on: ubuntu-latest
    steps:
      - name: download firefox artifact
        uses: actions/download-artifact@main
        with:
          name: firefox-dist.zip
          path: ./
      - name: Upload Release Asset
        id: upload_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build.outputs.upload_url }}
          asset_path: ./firefox-dist.zip
          asset_name: firefox-dist.zip
          asset_content_type: application/zip
